### ISSUE TITLE
json root in response 

### ISSUE THREAD

**Issue by hookercookerman** [dingbat/nsrails#18]
this is either not handled or document how to;

I am using ruby motion; I also like to include json roots;  (active_model_serializers sure does)

[__NSCFString objectForKey:]: unrecognized selector sent to instance 0xa483270 (RuntimeError)

**Comment by dingbat** [comment]
Can you be more specific or provide an example? Not sure what you mean by 'JSON roots.'

**Comment by hookercookerman** [comment]
"Activities" : [{},,{}]
On Jul 20, 2012 9:48 PM, "dan hassin" <
reply@reply.github.com>
wrote:

**Comment by dingbat** [comment]
You still aren't being very clear.

I'm guessing your server returns `"activities" : [ {}, {} ]` for `/activities`, and you are making a `remoteAll` call or something similar.

Right now NSRails just supports receiving `[ {}, {} ]` for `remoteAll` calls (i.e., accessing `/activities`).

Is this your issue? It's a pretty quick fix if that's the case, and I'll do it anyway, but the crash that you posted doesn't really make sense. Why would `objectForKey:` be called on a string?

Given your JSON response, NSRails should've crashed earlier trying to call `translateRemoteDictionariesIntoInstancesOfClass:` on a dictionary.

**Comment by hookercookerman** [comment]
sorry I sent that last explanation from my phone; note to self provide more detail; thanks for the fix;

**Comment by dingbat** [comment]
No problem
