### ISSUE TITLE
Naming models with multiple words

### ISSUE THREAD

**Issue by tomconroy** [dingbat/nsrails#23]
I had a rails model called `ChecklistItem` which mapped successfully with NSRails, but was behaving strangely. It would get the total number of items for a given `Checklist` and get the `remoteID` fine, but wouldn't display any other fields. Suspecting it was a naming problem I refactored `ChecklistItem` to be just `Item` and seems to be working fine.

**Comment by dingbat** [comment]
Surprised to hear that - there are tons of test cases involving models with multiple words. Will investigate further tonight. Thanks for submitting.

So your Rails model is still named `ChecklistItem` and you overrode `remoteModelName` in NSRails, or did you change both?

**Comment by tomconroy** [comment]
I changed both, tried to make sure I didn't change other things along the way. I still have other rails models with more than one word, will post here whether they are behaving the same way once I build them into NSRails

**Comment by dingbat** [comment]
Closing due to non-reproducibility and inactivity of this issue.

Feel free to reopen.
