### ISSUE TITLE
Silence debugging traffic and object responses

### ISSUE THREAD

**Issue by mdfdroid** [dingbat/nsrails#29]
Hi,  quick couple of questions/concerns.
1.  Is there any option to turn off the debugging traffic that is sent to the console?  I am working on a framework using NSRails, and if possible would be nice to silence the traffic in the console, for the sake of not flooding other peoples console that may use the framework.
2.  Maybe I do not fully understand what is going on with the rails object requests,  but at the moment I am submitting an object for creation.  Once the object is created, I have to then make a second call to find the object, since I need to use the objects ID for later methods.  Is there any way to access the responses when an object is created, so I do not have to do a second call to get the ID of the object?   I only see that NSError is available with the remoteCreateAsync. 

Thanks again for the great project.

**Comment by dingbat** [comment]
Hi there!
1. Yup. See Logging in NSRails.h. You should simply comment out `#define NSRLog 2` to silence all logs.
2. There's no need to make a second call to retrieve the object, nor do you have to get the response – NSRails does the work for you. After an object is created remotely, it'll automatically update its fields with whatever data the server returns. You should be able to just access `remoteID` with no problems after the request finishes successfully.

**Comment by mdfdroid** [comment]
1. Ok great! Don't know why I didn't see this before.  If I could just suggest that it be added in as a property to the NSRConfig?  It isn't a big issue or anything, but in my case,  I am leaving NSRails out of the framework as a third party library, so if someone is using the framework and they are using NSRails it won't interfere with their project.  Doing it this way would mean I would have to supply an edited version of NSRails with the project and if someone was using it all ready then it would just be overwritten.  
2. Wow... I can not believe I didn't realize this earlier...

Thanks!
