### ISSUE TITLE
NSRRequest error on 6.1

### ISSUE THREAD

**Issue by jessiahr** [dingbat/nsrails#33]
I use nsrails on may of my other projects however in 6.1 im getting "parse issue expected a type" on line 335 of NSRRequest.h:
- (void) sendAsynchronous:(NSRHTTPCompletionBlock)completionBlock;

Any idea why this would be happening?

![Screen Shot 2013-03-05 at 11 37 08 AM](https://f.cloud.github.com/assets/1097973/224120/292ec1c4-85cc-11e2-84a7-e9a9cfb2af25.png)

**Comment by dingbat** [comment]
Thanks for the report. That commit should fix it.

**Comment by jessiahr** [comment]
Thank you that fixed it!

And thank you for building this great tool!

p.s I have started working on something similar for javascript -> http://www.ratliffstudios.com/tools/

**Comment by dingbat** [comment]
No problem. And hey that looks cool, nice work!
