### ISSUE TITLE
Server error that isn't 422

### ISSUE THREAD

**Issue by pareeohnos** [dingbat/nsrails#43]
One thing I'm doing in the API of my application is to catch all exceptions that are thrown and handle them myself by returning JSON to the requesting app. This should be fine, but it seems NSRails is attempting to handle server errors automatically. 

This would be fine, however it's causing the app to crash as it's attempting to search HTML, when my response is in JSON. I am getting the error

```
[__NSDictionaryM rangeOfString:]: unrecognized selector sent to instance 0x9be99a0
```

Which is coming out of

```
- (NSError *) serverErrorForResponse:(id)response statusCode:(NSInteger)statusCode
```

in `NSRRequest.m` on line 375

```
if ([response rangeOfString:@"</html>"].location != NSNotFound)
```

It seems that by this point, response is no longer a string, and has already been parsed into a dictionary to match the response from my server. 

I think this should be altered so that it checks to see if the response is a dictionary, and if not, only then check for html, but even then check if it's an instance of NSString.

**Comment by dingbat** [comment]
You make a good point, thanks for bringing this up. It should be fixed now.

Remember that you can retrieve the JSON dictionary from the error's `userInfo` using the key `NSRErrorResponseBodyKey`.

**Comment by pareeohnos** [comment]
Ah nice! I'll check that out tomorrow. 
Yeah I'm using the `userInfo` dictionary for my errors, works perfectly, but the issue was that the app was crashing before I had a chance to access the dictionary, as the `NSRRequest` was trying to parse the response to actually populate the dictionary before it got to my code. 

I'll have a look at the commit tomorrow and let you know how it goes :) Thanks for the quick response!

**Comment by pareeohnos** [comment]
Works perfectly, thanks :D

**Comment by dingbat** [comment]
Cool, no problem!
