### ISSUE TITLE
Core data not saving?

### ISSUE THREAD

**Issue by pareeohnos** [dingbat/nsrails#47]
I'm not sure if I'm doing something wrong (most likely) but could you help me out again?

I've switched my models over the use core data (wasn't using it before now), so I've added my data model and added an entity for each of my models, I've also created an entity for the `NSRRemoteManagedObject` as it says you should in the core data guide, and I've added the remote id to that.

Each of my entities inherit from the NSRRemoteManagedObject in both the data model, and the actual classes.

The problem I'm now having is that the data isn't actually being saved to the database? I'm using the following code

```
[Location remoteAllViaObject:[[MGSettings sharedSettings] loggedInUser]
                       async:^(NSArray *allRemote, NSError *error) {
                           _locations = [NSMutableArray arrayWithArray:allRemote];
                           dispatch_async(dispatch_get_main_queue(), ^{
                               [_locationsTableView reloadData];
                               NSError *test;
                               [[[MGCoreDataManager sharedInstance] managedObjectContext] save:&test];
                               NSLog(@"Hey");
                           });
                       }];
```

I'm explicitly saving the context when the data is retrieved, but there is no data being saved in the database. 

Am I doing something wrong here? I've also definitely set the `#define` to use core data so I'm confused :(

**Comment by dingbat** [comment]
Strange, what you describe seems fine. Could you do some debugging?

Set a breakpoint in `remoteAllViaObject` and follow it through – it should eventually go through `objectWithRemoteDictionary` (the NSRRemoteManagedObject overridden one), and make its way to `initInserted`. Let me know if things go unexpectedly along the way.

-Dan

**Comment by pareeohnos** [comment]
hmm the fetch request in there seems to be retrieving the object so it is saved. I'm just confused then why I can't seem to see the data in  SQLite database viewer?

**Comment by dingbat** [comment]
Don't know, never used such a thing with CoreData. Closing this for now.
