### ISSUE TITLE
Existing nested properties preventing context save CoreData

### ISSUE THREAD

**Issue by pareeohnos** [dingbat/nsrails#48]
In my core data store, I have a user object with ID 16 saved already.
When I now try and do a remote create for a new object, it succeeds, and the Rails app responds accordingly. When NSRails handles the response, it finds a nested User object which is part of the response, and then correctly tries to create this user record.

The problem, is that when it encounters the user in the core data store, it fails due to the validation built into NSRails, and then doesn't save the context and doesn't then let me save it at any point after.

I know that I can disable the validation entirely, but I want the validation there. Is there a way I can simply remove it for this operation or is this a bug?

**Comment by pareeohnos** [comment]
Ignore! I missed something when I migrated to use the CoreData version, so it was attempting to create the user in the managedObjectContext when I was fetching it from the plist where it was stored, and THEN trying to create it at the same time later when it downloaded a user relation, and thus failed when it tried creating the record twice. 

Now I've changed the logged in user system to user the CoreData store as well, and it's working as expected :)

**Comment by dingbat** [comment]
Cool man.
