### ISSUE TITLE
Default date format changed in Rails 4

### ISSUE THREAD

**Issue by pareeohnos** [dingbat/nsrails#49]
It seems as though the default date format used in Rails 4 has changed, so the current version of NSRails doesn't parse dates and sets them all to nil. The new rails format (albeit not that different) is now

```
yyyy-MM-ddTHH:mm:ss.SSSZ
```

**Comment by dingbat** [comment]
Good catch, thanks. I'll be away from my computer for a few days so feel free to open a PR.

Until then I think there's a method on NSRConfig for date format ...

-Dan

**Comment by pareeohnos** [comment]
Yeah i've overridden it for now :)
I'll setup a pull request if I get some free time :)

**Comment by dingbat** [comment]
See #51.
