### ISSUE TITLE
shouldOnlySendIDKeyForNestedObjectProperty: tested against wrong object?

### ISSUE THREAD

**Issue by pareeohnos** [dingbat/nsrails#50]
I've just run into what I think is a bug with the way NSRails is testing whether an object should only submit the ID or the full object.

As per the documentation, I've overridden `shouldOnlySendIDKeyForNestedObjectProperty:` to return YES in my `User` class.

I have a `Trustee` class which has a `trustee` and a `truster` property, both of type `User`. I'm expecting to have a `remoteCreateAsync:` submit with `trustee_id` and `truster_id` but instead I'm getting an exception when trying to retrieve the remoteID from the object, on line `201` of `NSRRemoteObject.m`

If I'm understanding the code correctly, shouldn't

```
if ([self shouldOnlySendIDKeyForNestedObjectProperty:property])
{           
*remoteKey = [*remoteKey stringByAppendingString:@"_id"];
    return [val remoteID];
}
```

actually be

```
if ([val shouldOnlySendIDKeyForNestedObjectProperty:property])
{           
*remoteKey = [*remoteKey stringByAppendingString:@"_id"];
    return [val remoteID];
}
```

?? What's happening in my case, is that `self` is the Trustee object. When I do a `remoteCreateAsync:` and this method is fired, the `shouldOnlySendIDKeyForNestedObjectProperty:` is returning false, because it is checking against the `Trustee` object and not the `User` property. It then continues, tries convert the `User` into a dictionary, this method is then fired again for the `User`, where `shouldOnlySendIDKeyForNestedObjectProperty:` now returns `true`. It then attempts to call `[val remoteID]' but because`self`is now the`User`object, the property it is testing is a users property (in my case, the inverse relationship`trusters`), which`[val remoteID]`fails because it's an`NSFaultingMutableSet` instead of an individual object.

Hopefully this makes some kind of sense?

**Comment by dingbat** [comment]
If I'm understanding correctly...

`shouldOnlySendIDKeyForNestedObjectProperty:` should not be overridden in the object for which you only want the `id` key.

It should be overridden in the _parent object that's being sent_. This is why it is worded as "should I (the object being created) only send the ID key for this _nested object_, associated with _this property_?"

It's done this way so sending `id` is done on a case-by-case level (ie, property level). You wouldn't want all User objects ever to only be represented by their `id`.

The return value for `shouldOnlySendIDKeyForNestedObjectProperty:` should almost never be `YES` or `NO`, but rather something like:

```
- (BOOL) shouldOnlySendIDKeyForNestedObjectProperty:(NSString *)property
{
   return [property isEqualToString:@"trustee"];
}
```

Make sense?

**Comment by pareeohnos** [comment]
Ahhhhhhhh ok that makes sense :)

**Comment by pareeohnos** [comment]
Working as expected now :) Thanks for clearing that up
