### ISSUE TITLE
Additional support for custom methods

### ISSUE THREAD

**Issue by marklarr** [dingbat/nsrails#53]
In `NSRRemoteObject`, there's currently

``` objective-c
+ (NSArray *) remoteAll:(NSError **)error;
+ (id) remoteObjectWithID:(NSNumber *)mID error:(NSError **)error;
```

Which are great, because they know the class of object we're expecting, and automatically parse the response `JSON` into `NSObject`s for us.

It seems like it'd be nice to have this same sort of automagic parsing of the return available for custom methods? Something like...

``` objective-c
+ (NSArray *) remoteAllWithCustomMethod:(NSString *)customMethod andParams:(NSDictionary *)params:(NSError **)error;
+ (id) remoteObjectWithCustomMethod:(NSString *)customMethod andParams:(NSDictionary *)params error:(NSError **)error;
```

Unless I'm missing something, it seems like the only option right now is to make an `NSRRequest` with `- (id) routeToClass:(Class)c withCustomMethod:(NSString *)optionalRESTMethod`, and then fire that off, but all you get back is JSON.

Thoughts?

**Comment by marklarr** [comment]
@dingbat

**Comment by dingbat** [comment]
Yep, use NSRRequest.

Automagically convert using 
- [+[NSRRemoteObject objectWithRemoteDictionary:] ](http://dingbat.github.io/nsrails/Classes/NSRRemoteObject.html#//api/name/objectWithRemoteDictionary:) and
- [+[NSRRemoteObject objectsWithRemoteDictionaries:] ](http://dingbat.github.io/nsrails/Classes/NSRRemoteObject.html#//api/name/objectsWithRemoteDictionaries:)

passing in the JSON response.

**Comment by marklarr** [comment]
Makes sense. My only gripe would be that you already passed in the NSRRemoteObject subclass into NSRRequest (if you did routeToClass) , d then you have to specify it again once you get the return, as you demonstrated. Makes code a little more noisy than necessary, but perhaps a pedantic issue :), you can close if you'd like.

**Comment by dingbat** [comment]
Cool. Yeah, the NSRRequest class took a bit of designing. I think it's good in that it separates concerns, since it shouldn't really know anything about the subclass when sending the request, really only when setting up routes.

The code can get a little noisy, but I think the design principles are sound. What if the request returned a different kind of object? The class is designed to be flexible as possible (since the rest of NSRails relies on it), and doing custom stuff means getting gritty. I knew custom methods could also mean params, and maybe even some custom JSON, so I left it all up in the air. Hope you can agree!

**Comment by marklarr** [comment]
Hey, I definitely agree that `NSRRequest` should just take care of sending a raw request, getting the raw response. I actually really like the way that class is setup -- kudos. Just to make sure my original message was clear, I was proposing that it may be nice to add new methods onto `NSRRemoteObject`, allowing things like

`NSArray* tweets = [Tweet remoteAllWithCustomMethod:@"trending_tweets" params:@[ @"gender" : @"male" ]];`

rather than

``` objective-c
NSRRequest* req = [[NSRRequest GET] routeToClass:[Tweet class] withCustomMethod:@"trending_tweets"];
req.queryParameters = @[ @"gender" : @"male" ];
NSDictionary* json = [req sendSynchronous error:nil];
NSArray* tweets = [Tweet arrayOfInstancesFromRemoteJSON:json]; // Private method :(
```

Though, just writing this out, I see that these methods would need two more parameters -- `HTTPMethod` and `NSError`, making it more like

``` objective-c
NSArray* tweets = [Tweet remoteAllWithCustomMethod:@"trending_tweets" 
                                      params:@[ @"gender" : @"male"]
                                 httpMethod: NSRRequestGET
                                           error:nil];
```

_(PS - github does not make it easy to format that, for some reason)_

So, maybe not as elegant as I had originally envisioned.

Cheers!

**Comment by dingbat** [comment]
Ah, ok. I see. Well the example you give is pretty specific – imagine all the get/fetch/delete/etc-"withCustomMethod" possibilities. NSRails already has too big of a matrix for method combinations :)

But you do make a good point. And if this is something you find yourself doing often, of course you could add that method as a category. I just don't think this specific case is standard enough to include built-into the library, you know? (Then again I honestly haven't used NSRails for any terribly complex apps...)

**Comment by marklarr** [comment]
I agree - if this is sort of a unique thing, then it's probably best left up to a category. Maybe a good starting point is to make that arrayOfInstancesFromRemoteJSON method public, so we can access it from the category without too much hackery? :)

**Comment by dingbat** [comment]
Right, was going to ask about that – what's wrong with [+[NSRRemoteObject objectsWithRemoteDictionaries:]](http://dingbat.github.io/nsrails/Classes/NSRRemoteObject.html#//api/name/objectsWithRemoteDictionaries:)?

**Comment by dingbat** [comment]
is it just that "wrapper" check? might consider consolidating those two methods into one...

**Comment by marklarr** [comment]
Hey -- yep, just the wrapper check. It's pretty straight forward, but I die a little bit inside every time I copy+paste code. The consolidation sounds like a great idea. :+1:

**Comment by dingbat** [comment]
Done! Hope you're not using CocoaPods cause I don't feel like updating it :) feel free to do a PR with them if you are.

**Comment by marklarr** [comment]
Awesome! thanks
