### ISSUE TITLE
Array of objects cannot be sent as only ID when they're a property of an NSRRemoteObject

### ISSUE THREAD

**Issue by ndonnellan** [dingbat/nsrails#54]
If I have a property, say "responses", which is an array of nested NSRRemoteObjects inside of an NSRRemoteObject, like "post", and I want them to be sent as ID's only, the default implementation will throw an exception because of these line in encodeValueForProperty:remoteKey:

```
198   if ([self shouldOnlySendIDKeyForNestedObjectProperty:property]) 
199   {         
200        *remoteKey = [*remoteKey stringByAppendingString:@"_id"];
201        return [val remoteID];
202   }
```

In the case of the array property, it has no method remoteID, hence the exception. My current workaround is to just override encodeValueForProperty:remoteKey: checking for my array and collecting the IDs manually or calling super afterwards.

Am I doing something wrong? Note: I'm coming from RubyMotion, so I'm not confident in supplying a fix in Obj-C just yet :-) Thanks for the library, it's pretty awesome!

**Comment by dingbat** [comment]
Huh. Interesting case! Just wrote up some tests for it & fixing. But overriding encodeValueForProperty:remoteKey: was definitely the right way to go.

Thanks a bunch!

**Comment by dingbat** [comment]
The standard for the key here is just "responses_id" right?

**Comment by ndonnellan** [comment]
Actually, I'm not sure "responses_id" works versus just "responses", but Rails isn't my forte. I'm manually managing the updates. Super fast reply, dude!

**Comment by dingbat** [comment]
No problem! Looks like Rails likes the form "response_ids". Will fix.

**Comment by dingbat** [comment]
@ndonnellan see if that does it!

**Comment by ndonnellan** [comment]
Works like a charm. Thanks!
