### ISSUE TITLE
No Visible @interface for remoteFetchAll:async

### ISSUE THREAD

**Issue by rickygu** [dingbat/nsrails#55]
I've been getting this error after updating to the latest version of nsrails.

No visible @interface for 'NSMutableArray' declares the selector 'remoteFetchAll:async:'

Here is my code:

``` ObjectiveC
        NSMutableArray *myCrews = [[NSMutableArray alloc] init];

        [myCrews remoteFetchAll:[NSRCrew class] async:^(NSError* error){
            if (error){
                [AppDelegate alertForError:error];
            }
            else
            {
                //process data here
            }
        }];

```

**Comment by dingbat** [comment]
Hi! The NSMutableArray additions were removed, you should now use the `remoteAll` request class methods on your NSRRemoteObject subclass:

``` objc
[NSRCrew remoteAllAsync:^(NSArray *allRemote, NSError *error) {
    //...
}];
```

**Comment by rickygu** [comment]
cool thanks it solved the problem.
