### ISSUE TITLE
Requesting items with matching parameter

### ISSUE THREAD

**Issue by ericdmann** [dingbat/nsrails#56]
I have a Rails app running with a very large database (300,000+ items). I need to only request and have sent items with a matching email address. Each of my items have an  email address property.

What's the correct way to set this up in NSRails? The ruby setup (I think) is where I'm getting hung up. Thanks for any help!

**Comment by dingbat** [comment]
Like I said in our email correspondence, I would think the best way is via custom request (custom method in your controller with a corresponding route), that gets the search email address from the request (via JSON body or query), does a lookup with ActiveRecord, and renders the results in JSON.

This is all Rails-side though. See #53 for help on making a custom request via NSRails.

**Comment by ericdmann** [comment]
So, in the Rails console, when I would call something like Objects.where(:email => "myemail")
There's no way to request this from NSRails? Sorry for the simple (I'm new to Rails) questions.

**Comment by dingbat** [comment]
Yep, that, except in a controller method, and then you can 'render' the results (I think 'render objects.to_json', but it's been some time).

NSRails is simply a framework that communicates with a Rails/RESTful webserver, it can't do any querying that Rails doesn't do itself. All it does is make a URL request and convert the raw JSON result into mapped objects that you can use client-side. It's fully up to the webserver to make certain requests/features available to clients. Add a method to your Objects controller, and add a new route that calls that method on a given URL scheme, then call that custom method with NSRRequest as in #53.
