### ISSUE TITLE
Unsupported URL

### ISSUE THREAD

**Issue by macfree** [dingbat/nsrails#7]
HI Y'all!

First this looks like great useful stuff! It looks really easy when u get the basic to work.

I just started doing some rails / iphone app, but got a problem with "Unsupported URL"', while trying to send data to the db "orders".

NSErrorFailingURLStringKey=0.0.0.0:3000/orders
The db is migrated and up running when browsing 0.0.0.0:3000. Firewall on or off does not make a difference.

Do I need to prepare the db to accept external connection / data?
Do you need to prepare iOS Simulator?

**Comment by dingbat** [comment]
http:// :)

**Comment by macfree** [comment]
haha it works!  Thanks! I thought without would work as it does in chrome.

I also tried localhost:3000 first but didnt work aswell as 127.0.0.1 (without http). wellwell, thanks again for all awesomesness!

**Comment by dingbat** [comment]
Yeah those should work now too. No problem!
